config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts do
    resources :posts, except: :index
    collection do
      get 'search'
      get 'menu'
    end
  end
  resources :users, only: :show
  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user,optional: true
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader
  def self.search(search)
    if search
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  validates :nickname, presence: true, length: { maximum: 6 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables
  
  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
    @id_heart = "#heart-#{@post.id}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search, :menu]
  
  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    begin
      @post.save!
    rescue ActiveRecord::RecordInvalid => e
      puts e
    end
    redirect_to menu_posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def search
    @post = Post.search(params[:keyword])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to menu_posts_path
  end

  def menu
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(9)
  end

  private
  def post_params
    params.require(:post).permit(:title, :review, :content, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(9).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%# <script src="app/assets/javascripts/jquery.raty.js"></script> %>
  </head>
  <body>
  <body>
    <div id="wrapper">
    <header class="header">
      <div class="header__title">
        <%= link_to "Book Management", root_path, class: "header__title--text" %>
      </div>
      <div class="header__right">
        <% if user_signed_in? %>
          <%= link_to "トップ", root_path, class: "header__right--btn" %>
          <%= link_to "すべての投稿", menu_posts_path, class: "header__right--btn" %>
          <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
          <%= link_to "投稿する", new_post_path, class: "header__right--btn" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
        <% else %>
          <%= link_to "トップ", root_path, class: "header__right--btn" %>
          <%= link_to "すべての投稿", menu_posts_path, class: "header__right--btn" %>
          <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
          <%= link_to "会員登録", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
      </div>
    </header>
    <%# <div class="contents"> %>
      <%= yield %>
    <%# </div> %>
    <div class="footer">
      @2020 Book Management
    </div>
  </div>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= @post.id %>">
  <% if user_signed_in? %>
    <% if current_user.likes.find_by(post_id: @post.id) %>
      <%= link_to unlike_path(post.id), method: :delete, remote: true do %>
      <div class = "iine__button">❤️<%= @post.likes.count %> イイね！</div>
      <% end %>
    <% else %>
      <%= link_to like_path(@post.id), method: :post, remote: true do %>
      <div class = "iine__button">♡️<%= @post.likes.count %> イイね！</div>
      <% end %>
    <% end %>
  <% else %>
    <% if @post.likes.length > 0 %>
      <div class = "iine__button">❤️<%= @post.likes.count %> イイね！</div>
    <% else %>
      <div class = "iine__button">♡️<%= @post.likes.count %> イイね！</div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');
$("<%= @id_heart %>").removeClass('iine__button');
$("<%= @id_heart %>").addClass('iine__button');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');
$("<%= @id_heart %>").addClass('iine__button');
$("<%= @id_heart %>").removeClass('iine__button');

app/views/posts/_post.html.erb
<div class="main-content">  
  <div class="content-image-box">
    <%= link_to post_path(post.id) do %>
      <img src=<%= post.image %> class="content-image" >
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="new">  
  <div class="content-title">
    投稿の編集✏️
  </div>
  <%= form_with model: @post, class: :form, local: true do |form| %>
    <%= form.text_field :title, placeholder: :タイトルを記入してください, class: :form__title %>
    <ul class="form__review">
    <li class="form__review__left">
      評価：⭐️
    </li>
    <li class="form__review__right">
      <%= form.select :review, [ ["評価を選択してください",0], ["5.0",5], ["4.5", 4.5], ["4.0", 4.0] ,["3.5", 3.5], ["3.0", 3.0], ["2.5", 2.5], ["2.0", 2.0], ["1.5", 1.5], ["1.0", 1.0], ["0.5", 0.5]  ] %>
    </li>
    </ul>
    <%= form.text_area :content, placeholder: :感想を記入してください, class: :form__content %>
    
    <%= form.label :image, "画像をクリックすると変更できます", class: :Image %>
      <div id="img_field" onClick="$('#file').click()" >

        <% if @post.image.url.present? %>
          <div class="Image__box">
          <img src=<%= @post.image %> class="Image__box" >
          </div>
        <% else %>
          <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
        <% end %>

      </div>
    <%= form.file_field :image, class: :form__image, style: "display:none;", id: "file" %>
    <div class="flex">
    <%= form.submit '再投稿する', class: :"btn btn-success mt-4" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
 <div class="contents"> 
  <div class="top">
    <h1 class="top-title">Book Management</h1>
    <div class="copy">
      <p>あなたは読んだ本を覚えていますか？<br>
          記録して感想をシェアしませんか？
      </p>
    </div>
    <div class="top-btn">
      <% if user_signed_in? %>
        <%= link_to "投稿する", new_post_path, class: "top-btn__item" %>
      <% else %>
        <%= link_to "会員登録", new_user_registration_path, class: "top-btn__item" %>
        <%= link_to "ログイン", new_user_session_path, class: "top-btn__item" %>
      <% end %>
    </div>
  </div>
 </div> 

app/views/posts/menu.html.erb
<div class="menu">
  <div class="menu-bar">
    <div class="menu-bar__left">
      現在の投稿数は<strong><%= @posts.ids.length %></strong>件です。
    </div>
    <div class="search">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワードで投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "btn btn-light" %>
      <% end %>
    </div>
  </div>
  <h3>ユーザー投稿一覧</h3>
  <div class="menu-post">
    <% @posts.each do |post| %>
　  <%= render partial: "post", locals: { post: post } %>
    <% end %>
    
  </div>
    <%= paginate(@posts) %>
</div>

app/views/posts/new.html.erb
<div class="new">
  <div class="content-title">
    読んだ本について書こう📚
  </div>

  <%= form_with model: @post, class: :form, local: true do |form| %>
    <%= form.text_field :title, placeholder: :タイトルを記入してください, class: :form__title %>
    <ul class="form__review">
    <li class="form__review__left">
      評価：⭐️
    </li>
    <li class="form__review__right">
      <%= form.select :review, [ ["評価を選択してください",0], ["5.0",5], ["4.5", 4.5], ["4.0", 4.0] ,["3.5", 3.5], ["3.0", 3.0], ["2.5", 2.5], ["2.0", 2.0], ["1.5", 1.5], ["1.0", 1.0], ["0.5", 0.5]  ] %>
    </li>
    </ul>
    <%= form.text_area :content, placeholder: :感想を記入してください, class: :form__content %>
 
    <%= form.label :image, "クリックして画像を選択してください", class: :Image %>
      <div id="img_field" onClick="$('#file').click()" >

        <% if @post.image.url.present? %>
          <%= image_tag(@post.image.url) %>
        <% else %>
          <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
        <% end %>
 
      </div>
    <%= form.file_field :image, class: :form__image, style: "display:none;", id: "file" %>
    <div class="flex">
    <%= form.submit '投稿する', class: :"btn btn-success mt-4" %>
    </div>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="search-second">
  <div class="search-bar">
  <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "btn btn-light" %>
  <% end %>
  </div>
  <h3>検索結果</h3>
  <div class="search-post">
    <% @post.each do |post| %>
      <%= render partial: "post", locals: { post: post } %>
    <% end %>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show">
  <div class="postManage">
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-outline-secondary" %>
      <%= link_to "削除", post_path(@post.id), method: :delete, class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
  <div class="post">
    <div class="post__User">
      投稿者：<%= link_to @post.user.nickname, user_path(@post.user), class: "post__User__name" %>
        <div class="post__User__name__date">
          <%= @post.created_at.to_s(:datetime_jp) %>
        </div>
    </div>
    <div class="post-box">
      <div class="post-box__ImageBox">
        <img src=<%= @post.image %> class="post-box__ImageBox__Image" >
      </div>
      <div class= post-box__content>
        <div class="post-box__content__Title">
          <%= @post.title %>
        </div>
        <div class="post-box__content__Review">
          評価：⭐️<%= @post.review %>
        </div>
        <div class="post-box__content__Text">
          <%= simple_format @post.content %>
        </div>
        <%= render 'likes/like', post: @post %>
      </div>
    </div>
  </div>
  <div class="post-redirect">
    <%= link_to "投稿一覧へ戻る", menu_posts_path, class: "btn btn-outline-secondary" %>
  </div>
  <div class="post-redirect">
    <%= link_to "ホームへ戻る", root_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="menu">
  <div class="menu-bar">
    <div class="menu-bar__left">
      あなたは<strong><%= @posts.ids.length %></strong>冊の本を読んでいます。
    </div>
    <div class="search">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワードで投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "btn btn-light" %>
      <% end %>
    </div>
  </div>
  <h3><%= @user.nickname %>さんの投稿</h3>
  <div class="menu-post">
    <% @posts.each do |post| %>
　  <%= render partial: "/posts/post", locals: { post: post } %>
    <% end %>
  </div>
  <%= paginate(@posts) %>
</div>